### ISSUE TITLE
How to run unittest? Some testcase cannot pass.

### ISSUE THREAD

**Issue by inevity** [enigmampc/catalyst#113]
None.

**Comment by inevity** [comment]
run test: 
nosetests -w tests/exchange test_bundle:TestExchangeBundle.test_ingest_csv
result: 

/Users/baojg/Downloads/code/catalyst/catalyst/exchange/bundle_utils.py", line 289, in get_df_from_arrays
    ohlcv[field] = arrays[index].flatten()
TypeError: 'NoneType' object is not subscriptable

Then many boto s3 log, 
boto3.resources.factory: DEBUG: Loading s3:s3
test_exchange_bundle: DEBUG: to load raw arrays
test_exchange_bundle: WARNING: skipping ctable for bat_eth from 2017-06-03 00:00:00+00:00 to 2017-08-03 19:24:00+00:00: [Errno 2] No such file or directory: 'data/exchanges/bittrex/minute_bundle/57/05/570516.bcolz/open/meta/sizes

my question: who call the boto s3?

**Comment by fredfortier** [comment]
I believe that you are doing it right. We’re currently working improving
coverage on the develop branch at the moment. We’ve organized three test
suite all using data samples so we can easily tests across exchanges. I’m
not sure what’s calling s3 here, unless just importing the lib causes this.
We’ll take a look.

**Comment by fredfortier** [comment]
Fixed the s3 issue.

**Comment by inevity** [comment]
Thanks

**Comment by fredfortier** [comment]
We're doing some work on unit tests with the goal of having an automated test suite. Since there are many exchanges and markets which result in many edge cases which could go wrong, we're using a sampling method to avoid always testing against the same things.

Here are the first two test suites:
`tests/exchange/test_suite_bundle.py`
`tests/exchange/test_suite_exchange.py`

We're also adjusting the build-in Zipline tests to skip the non-applicable ones and ensure that the others pass. This will be ongoing for a little while but our goal is to reach 100% coverage.

**Comment by inevity** [comment]
Happy to know what you were doing. In fact, When run nosetest, too many error.

**Comment by lenak25** [comment]
We have been working on utilising the unit tests and integrating catalyst with travis, as documented [here](https://enigma.co/catalyst/development-guidelines.html#style-guide-running-tests).

This is a work in progress - more tests should be added from time to time to increase their coverage.
