### ISSUE TITLE
Unable to run algorithm downloaded from strategies

### ISSUE THREAD

**Issue by CabalKabob** [enigmampc/catalyst#149]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10`)
* Python Version: 2.7
* Python Bitness: 
* How did you install Catalyst: miniconda
* Python packages: 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
I followed the video instruction to install catalyst with miniconda. Everything went smoothly until...
I downloaded shannon's demon algorithm from the strategies page (https://www.enigma.co/catalyst/#/strategy/5976d5b1ffa4a8000449cac7). I try to back-test it on a currency. So I run the catalyst run the following command:
catalyst run -f shannons_demon_original.py -x bitfinex --start 2017-11-1 --end 2017-12-30 -c bch --capital-base 5000

* What did you expect to happen? 
Anything but error
* What happened instead?
I receive some errors. See attached for traceback details. 

Here is how you can reproduce this issue on your machine:

## Reproduction Steps
[ShannonsDemon_error_trace.txt](https://github.com/enigmampc/catalyst/files/1617597/ShannonsDemon_error_trace.txt)

1.
2.
3.
...

## What steps have you taken to resolve this already?
I try to ask the same question on discord, but nobody have suggested any solution
...

# Anything else?
No
...

Sincerely,
Terry

**Comment by fredfortier** [comment]
@lacabra does this sound familiar?

**Comment by treethought** [comment]
I've been experiencing this as well. My solution to get the algorithm running was to replace any instance of
```
data[context.asset].price
```
with
```
data.current(context.asset, 'close')
```

**Comment by lacabra** [comment]
Yes @treethought is correct. @CabalKabob please bear in mind that the algorithms that you'll find on the website you are referring to are dating back to August/September of 2017, and we have released a number of updates since then, one of which, in particular, changed the way you access the pricing data for a given asset, as outlined below.

My suggestion is that if you want to try sample algorithms you start with the ones you'll find here: https://enigmampc.github.io/catalyst/example-algos.html and https://github.com/enigmampc/catalyst/tree/master/catalyst/examples, which we keep up to date with the code.

Closing this issue given that this issue is more than 20 days old, and an a viable answer was provided. Reopen if needed.
