### ISSUE TITLE
[documentation] describe how a live trading algorithm can be interacted with

### ISSUE THREAD

**Issue by gatapia** [enigmampc/catalyst#185]
I am preparing to live trade but I have a few questions that should ideally be addressed in the docs.  Some of these questions are:

* Do you have to specify the `capital_base` when live trading, it appears that in paper trading mode it ignores this (another bug reported for this) and just uses the current balance.  This is bad for paper trading but perhaps good for live trading?
* Once an algo is running how can I stop it?  CTL+C seems a bit violent?  Can data be corrupted?  What if there are open orders.  What is the best practice here?  Perhaps in `handle_data` the algo should manually poll a file? i.e. create a `algo_namespace.stop` file in the algo directory and if the algo finds it then it can terminate gracefully?  How does an algo terminate gracefully?  Can we raise a StopAlgo exception or something like that?
* Once an algo is stopped and I want to cash part of my massive profits out of the exchange how do I then re-synchronise the algo?  Just start it again? Will it re-sync with its old state and recognise that balances have changed? (i.e. that is why I dont want to have the `capital_base`)
* Is it safe to take money out of the exchange while the algo is running?
* How can I view the results of a current running algo.  Is the 'results' object saved after each `handle_data`.  If so how can I access it?  Or can I query an internal database.  Currently I'm logging each transaction to a csv file and I can have live reports using these files but the `results` has so much more information that it would be good to be able to safely query it.

Cheers

**Comment by fredfortier** [comment]
> Do you have to specify the capital_base when live trading, it appears that in paper trading mode it ignores this (another bug reported for this) and just uses the current balance. This is bad for paper trading but perhaps good for live trading?

Yes, this would indeed be a bug in paper trading. You must specify it in all modes. If you capital base is higher the the currency amount in your wallet, the algo won't run in live mode.

>Once an algo is running how can I stop it? CTL+C seems a bit violent? Can data be corrupted? What if there are open orders. What is the best practice here? Perhaps in handle_data the algo should manually poll a file? i.e. create a algo_namespace.stop file in the algo directory and if the algo finds it then it can terminate gracefully? How does an algo terminate gracefully? Can we raise a StopAlgo exception or something like that?

We're intercepting the interrupt event to stop the algo gracefully. That said, I agree that it may not be the cleanest way to do it. Yes, we can add these types of events in future version but it's not there right now.

> Once an algo is stopped and I want to cash part of my massive profits out of the exchange how do I then re-synchronise the algo? Just start it again? Will it re-sync with its old state and recognise that balances have changed? (i.e. that is why I dont want to have the capital_base)
Is it safe to take money out of the exchange while the algo is running?

You can take money from the exchange at any time *as long as the remaining amount is higher or equal to position amount tracked by the algo*. If you sell more than that, the algo will readjust the position amount but it's not intended use and could affect your performance stats. We need to do more work on this. One of our next tasks is to serialize the state in JSON instead of just pickling the performance and position tracker objects, this will allow you to temper with the positions. For now, if you want to artificially change the positions held by an algo, you can clear the state `catalyst clean-algo -n my-algo` and start anew.

> How can I view the results of a current running algo. Is the 'results' object saved after each handle_data. If so how can I access it? Or can I query an internal database. Currently I'm logging each transaction to a csv file and I can have live reports using these files but the results has so much more information that it would be good to be able to safely query it.

Yes, look in the `~/.catalyst/data/live_algos/my-algo/stats/` folder and you'll find some pretty comprehensive stats. It tracks all variables registered with `record()` in addition to some general metrics. The files are broken down daily but contain a row for every frame. We'll document this feature better. Here is an example to illustrate how to record asset specific metrics:
```
asset = symbol('neo_eth')
prices = dict()
prices[asset] = data.current(asset, 'close')
record(price=prices)
```

**Comment by gatapia** [comment]
Thanks for the answers @fredfortier.  Is there any inbuilt exception I can throw to exit live trading mode programatically?  Or any other way I can tell the environment to halt?

**Comment by manelrovira** [comment]
In live mode you can use the order `context.interrupt_algorithm()`.

**Comment by gatapia** [comment]
Thanks @manelrovira, closing this for now as most of these items have been answered, thanks all

**Comment by Ericxgao** [comment]
Does the algorithm retain all variables within the context object? If I track state in there and restart the algorithm will they be reinitialized or retain the old value?

**Comment by fredfortier** [comment]
No, but it will track what you save in the `context.state` dictionary.

**Comment by kooomix** [comment]
Hi,

I've recently started running live trading tests, and there are some issues related with this thread that I'm still not sure about:

Let's say I run an algo with a certain namespace defined. I understand that if I stop and re-run the algo again without cleaning the namespace, it will go back to it's last state including all relevant positions made by previous run (assuming base_capital is equal or lower than existing capital).

But if I do clean the namespace, while in my exchange account I still have positions in place (either bought using previous algo runs or even manually) - is there a way to take them into account within my algo portfolio? Or if to generalize the question - can I load existing positions from my exchange account into a new fresh algorithm run?

Thanks

**Comment by lenak25** [comment]
Hi @kooomix , the situation you are describing is not possible by design.
When you are starting a new algorithm run from scratch, you are defining the algorithm parameters - like quote currency and capital base - which set your strategy boundaries, meaning that any existing position you might have, should not be disrupted by your strategy decisions.

**Comment by lenak25** [comment]
Thanks for the info @kooomix . 

I think that the main problem is the inconsistency you are experiencing in the algorithm state. It is important to investigate this, before we consider any workarounds for these problems.
Could you please open a new issue describing this?

Thanks,
Lena

**Comment by sam31415** [comment]
Just to link to issue #312, which is precisely requesting a way of modifying the portfolio object.
