### ISSUE TITLE
Installation via: python setup.py develop

### ISSUE THREAD

**Issue by frisitano** [enigmampc/catalyst#239]
When installing using the setup.py file via the command 'python setup.py develop' the installation hangs on the installation of ccxt and crashes on the installation of  bottleneck.  I installed these packages via pip and rerun 'python setup.py develop' and the installation completed successfully.

**Comment by EmbarAlmog** [comment]
Hi @frisitano, thanks for bringing up this issue. In order to get a better look on your issue, I need to know what are you trying to accomplish. 
In addition could you please share the following details:
* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`
Thank you

**Comment by EmbarAlmog** [comment]
Hi @frisitano I am closing this issue due to low activity. 
Feel free to reopen if there is still an issue.
