### ISSUE TITLE
Poloniex No Candles Issue

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#364]
Hi,

I've recently tried to run my algorithm in paper mode for Poloniex exchange. It was stopped by error, as it seemed, due to some sort of maintenance in poloniex.

Since then, and after poloniex were back live, I keep getting the below error for certain pairs:
"**Although requesting 30 candles until 2018-06-09 20:50:00+00:00 of asset TradingPair(750082 [omni_btc]), an empty list of candles was received for poloniex.**"

- Algo runs in '5T' frequency for data.history.
- Sporadic check indicates it may have something to do with pairs with no trades for the requested data period.. is that possible?

Thanks.

**Comment by lenak25** [comment]
Hi @kooomix, 

When requesting candles from exchanges in live mode we often request more candles than were defined in the algorithm in order to handle cases of low volume trading pairs which sometimes have missing candles. This error is received when even after requesting more candles than needed an empty list is received.
If can fit a case of an exchange maintenance in which no trading is performed so there are no candles to return.  
In any case, I've just tried to request `5T` history candles of `omni_btc` from Poloniex and received them without any error. You probably have experienced a temporary problem so I suggest you try again.  

Thanks,
Lena

**Comment by kooomix** [comment]
Thanks Lena.

So just to see if I get it right - if for example I want to get data from history for a certain pair, for 10 bars of frequency 30 minutes, than I should expect 10 data points, one for every 30 minutes. But if there were no trades for this pair in the past 1 hour, then even though I've set the bar to 10, I will only get 8 points of data... Is this how it works? Is there any relevant documentation describing how exactly data is being fetched using data.history in cases such as no trades?

**Comment by lenak25** [comment]
No @kooomix , in both cases you've described the number of bars will be 10. The difference is that in the second scenario the last two missing candles will be forward filled (by their previous candle).
So in order to being enable to forward fill in such cases, catalyst always request more past bars.
Hope it is clearer.

**Comment by kooomix** [comment]
Yes, now I get it, thanks!

**Comment by lenak25** [comment]
Happy to hear.
I am closing this, feel free to reopen if you need more clarifications.
