### ISSUE TITLE
CCXT: unable to fetch ticker bitfinex : bitfinex {"error":"ERR_RATE_LIMIT"}

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#394]
Hi,

I'm getting the above error when trying to fetch data.  It really seems like it is quite random among the symbols, and in any case, I never really make more than few requests per minute per symbols.

I've seen this issue being reported before, but still couldn't figure out how should this situation be handle...

Thanks

**Comment by lenak25** [comment]
Hi @kooomix ,

There are indeed some similar issues (as #196, #258) concerning Bitfinex which has a low rate limit and there are some planned improvements to catalyst to help dealing with it.
In the meantime, if you could be more specific in regards to what your algorithm is doing causing these errors, we could try to see if something can be done to bypass it.  

Lena

**Comment by kooomix** [comment]
Hi,

My algorithm make the following requests to bitfinex every 1 hour:
1. current volume for all symbols in one request data.current.
2. current price for all symbols in one request data.current.
3. data.can_trade for all symbols in one request.
4. historical volume for all symbols in one request data.history.
5. historical price for all symbols in one request data.history.

Notes:
*No problem with candles 1000 limitation.
*Not sure how many requests and of which type are being done by catalyst.
*Using dozens of symbols.

After additional tests I've conducted, I suspect the problem occurs only when using more than 5 symbols, regardless of the number of requests..

I hope this information is helpful, let me know how can I further help with the investigation.
Thanks

**Comment by lenak25** [comment]
Thanks for the information @kooomix .

As mentioned also at #196, when trying to assess the number of requests performed, you should take into consideration the following:

1. A different request is sent per each asset
2. At the current implementation: a different request is sent per each field - we plan to fix it ASAP.

Probably due to the low rate limit of Bitfinex, this exchange seems to be more vulnerable to these limitations.

Hope things are more clear now. 
We understand the improtance of fixing 2, but had to prioritize other things before, hope we could solve it in the coming releases. 

I am closing this issue as a duplicate of #196 to prevent confusion, feel free to continue this discussion there. 

Thanks,

Lena
