### ISSUE TITLE
Negative cash value

### ISSUE THREAD

**Issue by ddimkin** [enigmampc/catalyst#395]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Ubuntu 18.03)
* Python Version: `2.7`
* How did you install Catalyst: (`pip`)

Now that you know a little about me, let me tell you about the issue I am
having:
I implement my own decision strategy and insert it in an existing example https://github.com/enigmampc/catalyst/blob/master/catalyst/examples/dual_moving_average.py
For some reason, I got negative cash value.
![image](https://user-images.githubusercontent.com/34106312/42474636-8219941c-83c8-11e8-87b3-d13497b7a9cc.png)
 
I have a code like this(like in example as well):

    # Save values for later inspection
    record(price=price,
           cash=context.portfolio.cash,
           price_change=price_change,
           predicted_price=predicted_price)

    orders = context.blotter.open_orders
    if len(orders) > 0:
        return
    # Exit if we cannot trade
    if not data.can_trade(context.asset):
        return
    # We check what's our position on our portfolio and trade accordingly
    pos_amount = context.portfolio.positions[context.asset].amount
    # Trading logic
    if price > 10 and pos_amount == 0:
        # we buy 100% of our portfolio for this asset
        order_target_percent(context.asset, 1)
    elif price < 10 and pos_amount > 0:
        # we sell all our positions for this asset
        order_target_percent(context.asset, 0)

And in analyze I just have:

    # Fourth chart: Plot our cash
    ax4 = plt.subplot(414, sharex=ax1)
    perf.cash.plot(ax=ax4)
    ax4.set_ylabel('Cash\n({})'.format(quote_currency))
    start, end = ax4.get_ylim()
    ax4.yaxis.set_ticks(np.arange(0, end, end / 5))

Sincerely,
Dimkin

**Comment by SOGorman35** [comment]
I think that what you're seeing isn't really a bug, but rather, some really bad slippage from doing a market buy that filled at a bad price.

**Comment by ddimkin** [comment]
Any ideas how to fix it? May be I forgot to configure something..

**Comment by SOGorman35** [comment]
You have a few options.  The first would be to set a limit price, and change the buy percent from 100% to say, 99.8%, or whatever the amount would be minus fees.  The second would be to continue to use market buys, but set it from 100% to a lower amount that accounts for slippage.

The slight negative cash balances in backrests can be annoying, but keep in mind if you were simulating leverage in a backrest, your cash would be negative anyway, so it's understandable why it happens.  In live trading, you could keep it at 100%, but you'd want to set the allocated cash to be lower than the balance on the exchange in order to ensure that there is enough cash for the algorithm to keep running.
