### ISSUE TITLE
Poloniex has incorrect data

### ISSUE THREAD

**Issue by jshridha** [enigmampc/catalyst#430]
Dear Catalyst Maintainers,

# Description of Issue
The backtesting data for poloniex appears to have erroneous data. The price data for the last couple of days appears to be pegged at 296 ETH_USDT.
```
data.history(context.asset, fields='price', bar_count=100, frequency='5T').values

[296.2727899 296.2727899 296.2727899 296.2727899 296.2727899 296.2727899
 296.2727899 296.2727899 296.2727899 296.2727899 296.2727899 296.2727899
 296.2727899 296.2727899 296.2727899 296.2727899 296.2727899 296.2727899
 296.2727899 296.2727899 296.2727899]
```

I have tried to clean out the exchange data and reingest, but that has not helped. This problem appears to have started around the July 29th.

![figure_1](https://user-images.githubusercontent.com/11232787/43689377-925ac396-98c7-11e8-9834-a1839c3a903f.png)

Sincerely,
Jay

**Comment by lenak25** [comment]
Thanks for reporting @jshridha !
We will investigate this.

**Comment by lacabra** [comment]
The issue has been resolved. It was specific to the Poloniex exchange and it affected the majority of its currency pairs from midnight Jul 30th, 2018 onwards.

In order to remove any stale data you may have in your computer, please run:
`catalyst clean-exchange -x poloniex` 
to start fresh.

Here's a random sampling of the closing prices for 19 currency pairs from Poloniex for the entire month of August (which used to be a flat line, as reported above).

![poloniex](https://user-images.githubusercontent.com/6098973/45654457-ef74ba80-ba98-11e8-909f-4657156cb6e0.png)

**Comment by SOGorman35** [comment]
good news and bad news: the prices for the pairs that were on Poloniex prior to 07/29/2018 are once again current, but the coins (EOS, BAT) and new pairings (doge_usdt, etc.) that were added since then have no prices for daily or minute resolutions.

**Comment by SOGorman35** [comment]
Thanks.  I tested both daily and minute frequency for a few of the new coins, and got results this time.

**Comment by SOGorman35** [comment]
It would appear that Poloniex data isn't updating again.  IIRC, the last correct prices are from 12/15/2018.
