### ISSUE TITLE
Issue with the pairs mapped to different names in live trading mode 

### ISSUE THREAD

**Issue by msdyzdn** [enigmampc/catalyst#475]
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: `macOS 10.13.6`
* Python Version: `Python 3.6.5`
* Python Bitness: `64`
* How did you install Catalyst: `pip`
* Python packages: 
`aiodns==1.1.1
aiohttp==3.4.4
alembic==0.9.7
asn1crypto==0.24.0
async-timeout==3.0.0
attrdict==2.0.0
attrs==18.2.0
autobahn==18.9.1
Automat==0.7.0
bcolz==1.2.1
boto3==1.5.27
botocore==1.8.50
Bottleneck==1.2.1
cchardet==2.1.1
ccxt==1.17.94
certifi==2018.1.18
cffi==1.11.5
chardet==3.0.4
click==6.7
constantly==15.1.0
contextlib2==0.5.5
cryptography==2.2.2
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0.1
dateparser==0.7.0
decorator==4.3.0
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.5.20
eth-abi==1.2.0
eth-account==0.2.3
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==1.3.0
eth-utils==1.2.2
hexbytes==0.1.0
hyperlink==18.0.0
idna==2.6
idna-ssl==1.1.0
incremental==17.5.0
inflection==0.3.1
intervaltree==2.1.0
ipython-genutils==0.2.0
jmespath==0.9.3
jsonschema==2.6.0
jupyter-core==4.4.0
kiwisolver==1.0.1
Logbook==0.12.5
lru-dict==1.1.6
lxml==4.2.5
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
more-itertools==4.2.0
multidict==4.4.2
multipledispatch==0.4.9
nbformat==4.4.0
ndg-httpsclient==0.5.0
networkx==2.1
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
parsimonious==0.8.0
patsy==0.5.0
plotly==2.7.0
pyasn1==0.4.3
pyasn1-modules==0.2.2
pycares==2.3.0
pycparser==2.18
pycryptodome==3.6.6
PyHamcrest==1.9.0
pyOpenSSL==18.0.0
pyparsing==2.2.0
python-dateutil==2.7.3
python-editor==1.0.3
pytz==2016.4
Quandl==3.3.0
redo==1.6
regex==2018.8.29
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==1.0.2
s3transfer==0.1.13
scikit-learn==0.19.1
scipy==1.0.0
service-identity==17.0.0
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.2
statsmodels==0.8.0
TA-Lib==0.4.17
tables==3.4.2
toolz==0.9.0
traitlets==4.3.2
Twisted==18.7.0
txaio==18.8.1
tzlocal==1.5.1
urllib3==1.22
web3==4.4.1
websockets==5.0.1
wrapt==1.10.11
yarl==1.1.0
zope.interface==4.5.0`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
The pair of `NANOBTC` in Binance is mapped to `xrb_btc` in this package. the mapped pair is working well in the backtest mode. However, when using the algorithm in the live mode, it will try to fetch data for XRB/BTC pair from the Binance which is not existed. It returns the following error: 
`WARNING: CCXT: unable to fetch TradingPair(455142 [xrb_btc]) ohlcv: binance No market symbol XRB/BTC`

* What did you expect to happen?
 I expect it to use  `NANOBTC` pair instead of `XRBBTC`.

* What happened instead?
It uses `XRB/BTC` pair to fetch data.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. install catalyst from pip
2. run algorithm in live mode
3.  try to fetch current data or history data for this symbol ('xrb_btc')

Sincerely,
Masoud

**Comment by lenak25** [comment]
Hi @msdyzdn ,

Thanks for reporting this.
In catalyst 0.5.19 CCXT library version was upgraded, which [switched from using the XRB symbol to using the newer NANO symbol for the RaiBlocks token](https://github.com/ccxt/ccxt/issues/3302). 
However the problem was that catalyst bundles were not updated accordingly.
We've fixed it and aligned to the new CCXT standard: all pairs were switched to the new unified code `NANO`:
`XRB/BTC` is now `NANO/BTC`, `XRB/ETH` is now `NANO/ETH` and so on for live and backtest.

Right now, there might be a stale config file in your local system, which you can remove and clean by running `catalyst clean-exchange -x binance`.
Please note that all downloaded Binance historical data will be deleted using the `clean-exchange` command. Alternatively, you can manually remove the problematic file by deleting `~/.catalyst/data/exchanges/binance/symbols.json` file, or wait up to 24h, when it will be re-downloaded automatically.

In addition, you will need to re-ingest the `NANO/BTC` pair (and other `NANO` pairs) using the new labeling.

Thanks again for reporting this.

Lena
